### ISSUE TITLE
Basket is not initiated correctly in BaseController

### ISSUE THREAD

**Issue by Idleworks** [CommerceTeam/commerce#1]
I am on branch 67761 and trying to build a webshop with TYPO3 6.2.14.
I get an error at shopping cart's page after adding a product to basket:

Call to a member function getBasketHashValue() on a non-object in /typo3conf/ext/commerce/Classes/Controller/BaseController.php on line 265

**Comment by garbast** [comment]
There was an additional getBasket method that was not returning the correct object. This is fixed now
