### ISSUE TITLE
Next Commerce Version

### ISSUE THREAD

**Issue by garbast** [CommerceTeam/commerce#114]
Transfered from forge with Issue Number 56661

**Comment by garbast** [comment]
Andreas Allacher -
Hi,

any idea yet when these changes can be expected to be implemented?

**Comment by garbast** [comment]
Sebastian Fischer -
All of these features need sponsoring. Until each of the needed workload is individually sponsored, they won't get implemented.

**Comment by garbast** [comment]
Andreas Allacher -
How much do you need per hour?
And where can one sponsor, if one wants to do so? I might ask around and I would also be willing to sponsor too.

Also: Regarding Class names: do you also intend to change core class names from e.g. t3lib_div to GeneralUtility then? Because the current 6.2 branch still uses t3lib_div, ... classes.

#4

**Comment by garbast** [comment]
Andreas Allacher -
Another question: 
Would it be possible to implementiert some features myself and merge them back into the extension?

**Comment by garbast** [comment]
Sebastian Fischer -
Hi Andreas,
Everyone is invited to develop for Commerce. In general a issue is needed for every feature. As this project is still maintained via svn the changes should be provided as patch file. Afterwards we review it and if the quality as well as the features service a good purpose for commerce the patch get applied.

Before that it's always good to consider if the feature is interesting to other, or if it's only for your own project. Based on that decide if the extra amount work is worth it.

Greetings
Sebastian

**Comment by garbast** [comment]
Andreas Allacher -
OK. Great.

In that case I might try to implement some of the features (starting from current 6.2 compatible branch) mentioned in this ticket but it might take me a few weeks until I have time to start.

Regarding sponsoring: How can one sponsor, just write to Ingo at the ingo@typo3-commerce.org if one wants to sponsor - even if it is not the full amount I guess any amount could help in developing new fatures/bug fixes.
Or is there some PayPal sponsoring option or..?

P.S. any reason why the project is still SVN?

**Comment by garbast** [comment]
Andreas Allacher -
It took me a bit longer then intended but I finally started with my Website relaunch (using commerce) project and I might work on some of those features during or afterwards.
I guess it is enough to just create a github PR now? If so, I guess using the 67761 branch as that one includes the class renames?
Off-topic question: Should new tickets still be created here or github or are both OK?

Would fluid rendering completely remove current rendering or would current rendering be marked as deprecated (optional EM flag or something like that)?

**Comment by garbast** [comment]
Sebastian Fischer -
Hi Andreas,

your asumtions are correct. It would be ideal to habe Github pull requests and the recommended Branch to work on would 67761.

Fluid is a little bit more complecated. It would require to gather data for rendering in a completly different way. Futher more the rendering it self would happen in fluid and not in php any more.

To prevent processing overhead the old marker based rendering would get dropped it would be to much of a performance backlash to be accepted. Beside that the old rendering would need maintainents that is better invested in the fluid variant.

By now the change to fluid did not start and there has no funding be found, so its best bet that it will not happen the next 6 month.

Greetings
Sebastian

**Comment by AdlerBH99** [comment]
I think there are some companies interested (and depending on it) that this extensions will run on LTS 7. As one of these companies we are willing to take over some costs but there must be a plan for that. To my last E-mail to Ingo Schmidt i haven't received any feedback. 

... not in the next 6 months ... are really bad news and of course i understand that this is an open source project. 

Please set up a web page where people can apply for money support.

Cheers
Herbert

**Comment by garbast** [comment]
We were working on a whitepaper the last few weeks and will come up with a release of this shortly. We do our best to provide a precise plan on what and when to achieve a solution.

For times being i forward your request to Ingo.
