### ISSUE TITLE
when deleting products/categories wrong prices deleted

### ISSUE THREAD

**Issue by snillo** [CommerceTeam/commerce#119]
If a product or Category with products inside gets deleted, commerce deletes also the articles of the deleted products as well as the prices. But the wrong prices are deleted, see attached patch 
[commandMapHooks.php.txt](https://github.com/CommerceTeam/commerce/files/159786/commandMapHooks.php.txt)
file

This bug caused serious trouble in our installation since prices of random products were deleted and therefore the products didn't show up anymore in frontend

**Comment by garbast** [comment]
Thanks for reporting the issue. It's now fixed in master.

Can you please tell me what version of commerce you are using?

**Comment by snillo** [comment]
I'm using SVN revision r89173 (should correspond to Version 2.0.0)

**Comment by garbast** [comment]
Thanks for the information. Please try to update to master. There were a lot of fixes that only went into versions past 2.0. As long as you are updating up to TYPO3 6.2 everything should work.
