### ISSUE TITLE
Permission of child categories wrong

### ISSUE THREAD

**Issue by hannesbochmann** [CommerceTeam/commerce#122]
When a new category with a parent is saved in the backend, the permissions of the parent category aren't used correct. 
I think this is because the parent categories aren't loaded correct. In DataMapHooks::postProcessCategory around line 754 the uid of the parent categories is taken from the field parent_category. In former times the value of this field was a comma separated list of UIDs. Now it not only contains the UIDs but also a prefix of the table. So I got something like tx_commerce_categories_123. As this value is parsed as integer it will always result in the cateogry UID of 0 thus the permissions can't be loaded correct.

I'm not sure if this is a problem of commerce or just with my environment. But changing the line 
$uid = (int) $newParents[$keys[$i]];
to
$uid = $newParents[$keys[$i]];
$uid = (int) str_replace('tx_commerce_categories_', '', $uid);
fixes the problem for me. I think there can be more side effects.

So the first question is whether the content of the field parent_category is wrong or right in my case.

**Comment by hannesbochmann** [comment]
As there seem to be more problems with that, I think the prefix shouldn't be there. As a hotfix I changed the method DataMapHooks:preProcessCategory to the following:

        $categories = array_diff(
            GeneralUtility::trimExplode(',', $incomingFieldArray['parent_category'], true),
            array($id)
        );

        foreach ($categories as $key => $category) {
        	$categories[$key] = (int) str_replace('tx_commerce_categories_', '', $category);
        }

        $incomingFieldArray['parent_category'] = !empty($categories) ? implode(',', $categories) : null;

        $this->catList = $this->belib->getUidListFromList($categories);

        return $incomingFieldArray;

The same problem occurs for the category selection in products. So maybe there is something wrong with TreeView.

**Comment by hannesbochmann** [comment]
I did some more research. Now I think the prefix is correct but is not handled correct. There seem to be some method calls missing.

In DataMapHooks::postProcessProduct (around line 935) the following
            $newCats = $this->singleDiffAssoc(
                GeneralUtility::trimExplode(',', GeneralUtility::uniqueList($data['categories'])),
                $parentCategories
            );
should become
            $newCats = $this->singleDiffAssoc(
                GeneralUtility::trimExplode(',', GeneralUtility::uniqueList($data['categories'])),
                $parentCategories
            );

In DataMapHooks::postProcessCategory (around line 742) the following
$newParents = array_diff(explode(',', $fieldArray['parent_category']), $existingParents);
should become 
$newParents = array_diff($this->belib->getUidListFromList(explode(',', $fieldArray['parent_category'])), $existingParents);

If that's correct I can submit a pull request if you like. But I can imagine that there are even more spots where this problem comes in place.

**Comment by hannesbochmann** [comment]
I think I found other places of this bug. 

Around line 822 in DataMapHooks::postProcessCategory the line 
`$catUids = GeneralUtility::intExplode(',', $fieldArray['parent_category']);`
should become 
`$catUids = $this->belib->getUidListFromList(GeneralUtility::explode(',', $fieldArray['parent_category']));`

Around line 786 the following 
`$fieldArray['parent_category'] = GeneralUtility::rmFromList(
                            $uid,
                            $fieldArray['parent_category']
                        );`
should become
`$fieldArray['parent_category'] = GeneralUtility::rmFromList(
                            $uid,
                        	$this->belib->getUidListFromList(GeneralUtility::explode(',', $fieldArray['parent_category']))
                        );`

Around line 716 the following 
`$fieldArray['parent_category'] = GeneralUtility::uniqueList($fieldArray['parent_category']);`
should become
`$fieldArray['parent_category'] = implode(',', $this->belib->getUidListFromList(explode(',', GeneralUtility::uniqueList($fieldArray['parent_category']))));`

**Comment by hannesbochmann** [comment]
ping

**Comment by evoWeb** [comment]
I need to find time to fix this. If you have an working solution feel free to make a pull request.
