### ISSUE TITLE
Missing space in BasicDaoMapper.php

### ISSUE THREAD

**Issue by sir-gawain** [CommerceTeam/commerce#126]
Line 253 must be
        $res = $database->exec_SELECTquery('*', $this->dbTable, 'uid = ' . (int) $uid . ' AND deleted = 0');
Currently its
        $res = $database->exec_SELECTquery('*', $this->dbTable, 'uid = ' . (int) $uid . 'AND deleted = 0');
which results in a syntax error in the query.

**Comment by evoWeb** [comment]
Fixed
