### ISSUE TITLE
Cannot load class

### ISSUE THREAD

**Issue by sir-gawain** [CommerceTeam/commerce#127]
After installing sr_feuser_register i get the following error:

PHP Fatal error:  Class 'EXT:commerce/Classes/Hook/SrfeuserregisterPi1Hook.php:CommerceTeam\\Commerce\\Hook\\SrfeuserregisterPi1Hook' in Classes/Utility/GeneralUtility.php on line 4469.

i'm using TYPO3 6.2.25 and PHP 5.5 with autoloader.

I fixed this by changing the lines 
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sr_feuser_register']['tx_srfeuserregister_pi1']['registrationProcess'][] =
    'EXT:commerce/Classes/Hook/SrfeuserregisterPi1Hook.php:CommerceTeam\\Commerce\\Hook\\SrfeuserregisterPi1Hook';

to

$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sr_feuser_register']['tx_srfeuserregister_pi1']['registrationProcess'][] =
    'CommerceTeam\\Commerce\\Hook\\SrfeuserregisterPi1Hook';

I'm not sure if this is the correct fix for that, but at least for my needs it worked.

**Comment by sir-gawain** [comment]
I'm not sure, if all other hooks in this file need to be changed too.

Perhaps this is only an issue with newer versions of sr_feuser_register? They use (currently) makeInstance(), but this does not load class references like "EXT:file:class". Maybe older versions used getUserObj()?

**Comment by garbast** [comment]
All hooks that are commerce related are working as is.

But feel free to hand in a pull request that changes this configuration and is tested and working in your installation.

**Comment by sir-gawain** [comment]
Ok, that thats fine for me.
