### ISSUE TITLE
BasketController::$basket should be available in hooks

### ISSUE THREAD

**Issue by sir-gawain** [CommerceTeam/commerce#133]
If you want to use the Hook BasketController::generateBasketMarker, you get the marker array, a pointer to the BasketController and the template as parameters. But not the basket.
Both BasketController::$basket and BaseController::getBasket() are protected.

I wanted to replace ###BASKET_NEXTBUTTON### depending on the amount of articles in the basket.
Finally i made $basket public in my installation.

Is there a reason, why $basket and getBasket() are protected?

**Comment by garbast** [comment]
Base::getBasket is only a wrapper function. See

    protected function getBasket()
    {
        return $this->getFrontendUser()->tx_commerce_basket;
    }

Wrapper functions should never be public.

**Comment by sir-gawain** [comment]
Then BasketController has no getter function for the basket at all. getFrontendUser() is also protected. 
At the end i would have this in my code to access the basket from the BasketController in my hook:
$basket = $GLOBALS['TSFE']->fe_user->tx_commerce_basket;
This is simply very bad OOP.
$basket = $basketController->getBasket();
is what i would expect to work.

**Comment by garbast** [comment]
This is no OOP at all in this part because you want to have a singleton and this is registered in the frontend user. Feel free to have it in your hook but the api will not be changed for this.
