### ISSUE TITLE
automatic price calculation doesn't affect

### ISSUE THREAD

**Issue by calien666** [CommerceTeam/commerce#138]
the calculation of the prices in articles (from net, from gross, non existing) doesn't have any effect at all. After debugging, I found out, that the hook is registered wrong. Formerly the  TcehooksHandlerHooks was registered this way:
`$TYPO3_CONF_VARS['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processDatamapClass'][] = 'EXT:commerce/hooks/class.tx_commerce_tcehooksHandler.php:tx_commerce_tcehooksHandler';
$TYPO3_CONF_VARS['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processCmdmapClass'][] = 'EXT:commerce/hooks/class.tx_commerce_tcehooksHandler.php:tx_commerce_tcehooksHandler';`
now it is registered this way:
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tceforms.php']['getSingleFieldClass']['commerce'] =
 'EXT:commerce/Classes/Hook/TcehooksHandlerHooks.php:CommerceTeam\\Commerce\\Hook\\TcehooksHandlerHooks';`

For me it worked, to change the registration like the following:

`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processDatamapClass']['commercehooks'] =
    'EXT:commerce/Classes/Hook/TcehooksHandlerHooks.php:CommerceTeam\\Commerce\\Hook\\TcehooksHandlerHooks';`
and
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processCmdmapClass']['commercehooks'] =
    'EXT:commerce/Classes/Hook/TcehooksHandlerHooks.php:CommerceTeam\\Commerce\\Hook\\TcehooksHandlerHooks';`

In affect to this, the value is now multiplied by 100 two times, so in Classes/Hooks/TcehooksHandlerHooks.php the line 56 is changed as followed:

from:
`$incomingFieldArray[$key] = (int) strval($value * 100)`

to 

`$incomingFieldArray[$key] = (int) strval($value)`

alternatively the lines 51 to 59 are commented out.

**Comment by garbast** [comment]
Feel free to send a pull request
