### ISSUE TITLE
Foreign language products is handled wrong (fix included)

### ISSUE THREAD

**Issue by guppy42** [CommerceTeam/commerce#19]
If you have a shop where products are in 1 language ( default language, L:0 ) but with some products only existing in a different language ( L:1 ) those products are now only displayed when the shop is showing ( L:0 ) and not when the shop is showing that language ( L:1 ) because it's not translated.

This simple fix allows you to have products in any language and only having them show up if that language is selected - if that product is later translated to the default language this also works as expected;

https://github.com/CommerceTeam/commerce/blob/master/Classes/Domain/Repository/CategoryRepository.php#L365

change
`'SELECT' => 'tx_commerce_products.uid',`
to
`'SELECT' => 'tx_commerce_products.uid, tx_commerce_products.sys_language_uid',`

https://github.com/CommerceTeam/commerce/blob/master/Classes/Domain/Repository/CategoryRepository.php#L403

change
`if ($languageUid == 0) {`
to
`if ($languageUid == $row['sys_language_uid']) {`

**Comment by evoWeb** [comment]
Sorry for turning this issue down, but the the approach does not fix the problem. Instead it makes it more broken.

To be clear what should happen.
1. the products with language uid 0 of a given category should get loaded.
2. in case $languageUid is 0 the uid should be returned.
3. in case $languageUid is > 0 the uid of the product translation defined by l18n_parent == $uid and sys_language_uid = $languageUid should be returned if available

So following these rules the where part of the first query should have sys_language_uid = 0 added. It could be part of the result but thats unnecessary. The condition in the loop is fine as is.

For more clarification please contact me on slack either in direct message or in the commerce channel.

**Comment by guppy42** [comment]
Since I can only seem to create a new team on slack.com? I'll just ask you here;

I don't understand how it's "more broken" - it works, I'm running a shop using the change, how ever the change you added two hours ago, breaks it - intentionally it seems

https://github.com/CommerceTeam/commerce/blob/master/Classes/Domain/Repository/CategoryRepository.php#L332
` AND tx_commerce_products.sys_language_uid = 0 `


So I take it that supporting product with a base language != 0 is not something that the shop will be supporting?

Just to give an example of why that would be useful;

If you have an english shop that sell some products only in german ( like books/movies only available in german ) and would like not to show them to english customers who might accidentally buy them.


with out the ability to have a different base language you would need either;

a different shop trees - for each language

or

use a "sacrificial" language as default (and not use this in the shop), and translate every products in the real default language.


Both seem really cumbersome compare to the elegant solution of being able to have a base product having a meaningful language.


If it indeed intentionally not supported, then I will of course respect that and put my changes in an XCLASS - I just want to make sure we understand each other :)

**Comment by evoWeb** [comment]
I understood your scenario. There is one concern that i have with parentless translations. These cant have any category assigned. So its not possible to select oder change the category, even though you can add a product with a language choosen to a category.

So the current change is only to ensure that the translation handling is used as intended.

For getting access to typo3.slack.com please use https://forger.typo3.org/slack for the invite.
