### ISSUE TITLE
Unable to remove attributes from category or products

### ISSUE THREAD

**Issue by garbast** [CommerceTeam/commerce#34]
Once a product or category has been given a (select) attribute it's no longer possible to remove all of those attributes you can exchange the last attribute but removing all articles and saving will result in no change.

Transfered from forge with Issue Number 5382

**Comment by garbast** [comment]
Ralf Merz -
Hi,

i could still reproduce that. The last attribute, no matter in which correlation field, can not be removed.
So in lib/class.tx_commerce_belib.php->saveRelations() i added:

    // ralf: no attributes are set, so delete all attribute relations of this product
        if (empty($relationData)) {
            $GLOBALS['TYPO3_DB']->exec_DELETEquery(
                $relationTable,
                'uid_local=' .$uid_local .$where
            );
        }
          // end ralf

        if ($delete && (count($delWhere) > 0)) {
            $where = '';
            if (count($delWhere) > 0)    {
                $where = ' AND NOT ((' .implode(') OR (', $delWhere) .'))';
            }
            $GLOBALS['TYPO3_DB']->exec_DELETEquery(
                $relationTable,
                'uid_local=' .$uid_local .$where
            );
        }

So, if there´s no relationData, there are no selected attributes, and the mm-Relations can be deleted.
Do you think that´s ok?
For me, it now works.

Regards
Ralf 
(merzilla)

**Comment by garbast** [comment]
Stephan Brun -t
I had the same problem. Ralfs solution seems to work.

**Comment by garbast** [comment]
Fabian Auer -
Stephan Brun wrote:

I had the same problem. Ralfs solution seems to work.

Yep, solution works for me too. Thanks Ralf!

**Comment by calien666** [comment]
same problem exists in current version, fix helps again
