### ISSUE TITLE
Set some protected methods to public for easier hook usage

### ISSUE THREAD

**Issue by Idleworks** [CommerceTeam/commerce#5]
Was there a reason to define important methods like BaseController->getFrontendController() protected? 
My struggle: I am using hook in BasketController->makePayment to override rendering of payment's select box and paymentAllowedArticles and I don't have read/write access to customer's basket (want to use build in methods instead of $GLOBALS['TSFE']->fe_users->tx_commerce_basket).

My suggestions of methods to be public:
BaseController->getPaymentObject()
BaseController->getFrontendController()
BaseController->getFrontendUser()
BaseController->getBasket()

**Comment by evoWeb** [comment]
Hi Philipp,

getFrontendController, getFrontendUser and getBasket are only methods to
provide $GLOBALS[*] objects. These kind of getters are not part of the
api but provide core objects to be used in the specific classes. Thats
why these should never be public available. If you need these objects
you can easily implement them on yourown.

The payment object cant be obtained with

$config =
SettingsFactory::getInstance()->getConfiguration('SYSPRODUCTS.PAYMENT.types.'
. $paymentType);
$paymentObject = GeneralUtility::makeInstance($config['class'], $this);

In general i think we need some factory for these functionality instead
of opening up methods that do not realy belong to the scope of a
controller. But there are some other tasks more imported before i start
tackle that.

Greetings
Sebastian


Am 25.07.2015 um 14:49 schrieb Philipp Idler:
