### ISSUE TITLE
Warning when creating new product

### ISSUE THREAD

**Issue by hannesbochmann** [CommerceTeam/commerce#6]
I get an warning when creating a new product. array_unique expects parameter 1 to be an array. I think a simple cast to an array will fix it.
Line 749 in Tx_Commerce_Domain_Model_Category
$this->products_uid = array_unique($this->databaseConnection->getChildProducts($this->uid, $this->lang_uid));
becomes
$this->products_uid = array_unique((array) $this->databaseConnection->getChildProducts($this->uid, $this->lang_uid));

**Comment by garbast** [comment]
getChildProducts now always returns an array.

Only way this is not an array is if a hook productQueryPostHook was registered. If the result of this method is no array the error could happen.
