### ISSUE TITLE
Error when creating new product

### ISSUE THREAD

**Issue by hannesbochmann** [CommerceTeam/commerce#7]
I have an empty option already selected in the category selection upon new products. For editors this may lead to an error because of missing rights as the empty entry has the uid 0.
In Tx_Commerce_ViewHelpers_TceFunc line 214
$itemArray = array($category->getUid() . '|' . $category->getTitle()); 
becomes 
if ($category->getUid() > 0) {
						$itemArray = array($category->getUid() . '|' . $category->getTitle());
					}

**Comment by garbast** [comment]
Condition added
