### ISSUE TITLE
missing searchFields configuration in the TCA

### ISSUE THREAD

**Issue by hannesbochmann** [CommerceTeam/commerce#8]
$GLOBALS['TCA']['tx_commerce_products']['ctrl']['searchFields'] etc. is missing. That's why no elements from the extension can be found with the search in the BE. I think at least the products and categories should be searchable.

$GLOBALS['TCA']['tx_commerce_products']['ctrl']['searchFields'] = 'title, subtitle, navtitle, description';
$GLOBALS['TCA']['tx_commerce_categories']['ctrl']['searchFields'] = 'title, subtitle, navtitle, description, keywords';

**Comment by garbast** [comment]
Added 'uid, title, subtitle, navtitle, description' to both products and categories.
